import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// 1. Import the AuthProvider and your Navbar
import { AuthProvider } from "@/context/AuthContext";
import localFont from "next/font/local";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const montserrat = localFont({
  src: "../public/fonts/montserrat.ttf",
  variable: "--font-montserrat",
});

const opensans = localFont({
  src: "../public/fonts/opensans.ttf",
  variable: "--font-opensans",
});

const helvetica = localFont({
  src: "../public/fonts/helvetica.ttf",
  variable: "--font-helvetica",
});

export const metadata: Metadata = {
  title: "Radion-Lung Cancer Detection",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${helvetica.variable} ${opensans.variable}  antialiased`}
      >
        <AuthProvider>
          <Navbar/>
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
